name: ejecutar mvn
on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Chequear repositorio
              uses: actions/checkout@v2

            - name: Configurar Java JDK 8
              uses: actions/setup-java@v2
              with:
                java-version: '8'
                distribution: 'temurin'
                cache: 'maven'

            - name: Ejecutar mvn clean install
              run: mvn clean install

            - name: Mostrar contenido del directorio target
              run: ls -la target/